# Generated by Django 3.0.6 on 2020-12-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variableData', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='weatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variableData', models.CharField(max_length=200)),
            ],
        ),
    ]
