const CMIP5Table =[
{label: "3hr"},
{label: "3hrCurt"},
{label: "3hrMlev"},
{label: "3hrPlev"},
{label: "3hrSlev"},
{label: "6hrLev"},
{label: "6hrPlev"},
{label: "Aclim"},
{label: "Amon"},
{label: "AmonExtras"},
{label: "LIclim"},
{label: "LImon"},
{label: "Lclim"},
{label: "Lmon"},
{label: "OIclim"},
{label: "OImon"},
{label: "Oclim"},
{label: "Omon"},
{label: "OmonExtras"},
{label: "Oyr"},
{label: "OyrExtras"},
{label: "aero"},
{label: "cf3hr"},
{label: "cfDay"},
{label: "cfMon"},
{label: "cfOff"},
{label: "cfSites"},
{label: "day"},
{label: "dayExtras"},
{label: "fx"},
{label: "sites"},
]

export default CMIP5Table;