const CMIP5Table =[
{id: "CMIP5Table1", label: "3hr"},
{id: "CMIP5Table2", label: "3hrCurt"},
{id: "CMIP5Table3", label: "3hrMlev"},
{id: "CMIP5Table4", label: "3hrPlev"},
{id: "CMIP5Table5", label: "3hrSlev"},
{id: "CMIP5Table6", label: "6hrLev"},
{id: "CMIP5Table7", label: "6hrPlev"},
{id: "CMIP5Table8", label: "Aclim"},
{id: "CMIP5Table9", label: "Amon"},
{id: "CMIP5Table10", label: "AmonExtras"},
{id: "CMIP5Table11", label: "LIclim"},
{id: "CMIP5Table12", label: "LImon"},
{id: "CMIP5Table13", label: "Lclim"},
{id: "CMIP5Table14", label: "Lmon"},
{id: "CMIP5Table15", label: "OIclim"},
{id: "CMIP5Table16", label: "OImon"},
{id: "CMIP5Table17", label: "Oclim"},
{id: "CMIP5Table18", label: "Omon"},
{id: "CMIP5Table19", label: "OmonExtras"},
{id: "CMIP5Table20", label: "Oyr"},
{id: "CMIP5Table21", label: "OyrExtras"},
{id: "CMIP5Table22", label: "aero"},
{id: "CMIP5Table23", label: "cf3hr"},
{id: "CMIP5Table24", label: "cfDay"},
{id: "CMIP5Table25", label: "cfMon"},
{id: "CMIP5Table26", label: "cfOff"},
{id: "CMIP5Table27", label: "cfSites"},
{id: "CMIP5Table28", label: "day"},
{id: "CMIP5Table29", label: "dayExtras"},
{id: "CMIP5Table30", label: "fx"},
{id: "CMIP5Table31", label: "sites"},
]

export default CMIP5Table;