const CMIP5Model =[

    {	id:	"CMIP5Model1",	label:	"ACCESS1.0"	},
    {	id:	"CMIP5Model2",	label:	"ACCESS1.3"	},
    {	id:	"CMIP5Model3",	label:	"BCC-CSM1.1"	},
    {	id:	"CMIP5Model4",	label:	"CCSM4"	},
    {	id:	"CMIP5Model5",	label:	"CFSv2-2011"	},
    {	id:	"CMIP5Model6",	label:	"CMCC-CESM"	},
    {	id:	"CMIP5Model7",	label:	"CMCC-CM"	},
    {	id:	"CMIP5Model8",	label:	"CMCC-CMS"	},
    {	id:	"CMIP5Model9",	label:	"CNRM-CM5"	},
    {	id:	"CMIP5Model10",	label:	"CNRM-CM5-2"	},
    {	id:	"CMIP5Model11",	label:	"COSMOS-ASO"	},
    {	id:	"CMIP5Model12",	label:	"CSIRO-Mk3.6.0"	},
    {	id:	"CMIP5Model13",	label:	"CSIRO-Mk3L-1-2"	},
    {	id:	"CMIP5Model14",	label:	"CanAM4"	},
    {	id:	"CMIP5Model15",	label:	"CanCM4"	},
    {	id:	"CMIP5Model16",	label:	"CanESM2"	},
    {	id:	"CMIP5Model17",	label:	"EC-EARTH"	},
    {	id:	"CMIP5Model18",	label:	"EC-EARTH-2-2"	},
    {	id:	"CMIP5Model19",	label:	"ECHAM6-1-05-LR"	},
    {	id:	"CMIP5Model20",	label:	"FGOALS-g2"	},
    {	id:	"CMIP5Model21",	label:	"FGOALS-gl"	},
    {	id:	"CMIP5Model22",	label:	"FGOALS-s2"	},
    {	id:	"CMIP5Model23",	label:	"GEOS-5"	},
    {	id:	"CMIP5Model24",	label:	"GEOSCCM"	},
    {	id:	"CMIP5Model25",	label:	"GFDL-CM2.1"	},
    {	id:	"CMIP5Model26",	label:	"GFDL-CM3"	},
    {	id:	"CMIP5Model27",	label:	"GFDL-ESM2G"	},
    {	id:	"CMIP5Model28",	label:	"GFDL-ESM2M"	},
    {	id:	"CMIP5Model29",	label:	"GFDL-HIRAM-C180"	},
    {	id:	"CMIP5Model30",	label:	"GFDL-HIRAM-C360"	},
    {	id:	"CMIP5Model31",	label:	"GISS-E2-H"	},
    {	id:	"CMIP5Model32",	label:	"GISS-E2-H-CC"	},
    {	id:	"CMIP5Model33",	label:	"GISS-E2-R"	},
    {	id:	"CMIP5Model34",	label:	"GISS-E2-R-CC"	},
    {	id:	"CMIP5Model35",	label:	"HadCM3"	},
    {	id:	"CMIP5Model36",	label:	"HadGEM2-A"	},
    {	id:	"CMIP5Model37",	label:	"HadGEM2-AO"	},
    {	id:	"CMIP5Model38",	label:	"HadGEM2-CC"	},
    {	id:	"CMIP5Model39",	label:	"HadGEM2-ES"	},
    {	id:	"CMIP5Model40",	label:	"INM-CM4"	},
    {	id:	"CMIP5Model41",	label:	"IPSL-CM5A-LR"	},
    {	id:	"CMIP5Model42",	label:	"IPSL-CM5A-MR"	},
    {	id:	"CMIP5Model43",	label:	"IPSL-CM5B-LR"	},
    {	id:	"CMIP5Model44",	label:	"KCM1-2-2"	},
    {	id:	"CMIP5Model45",	label:	"MIROC-ESM"	},
    {	id:	"CMIP5Model46",	label:	"MIROC-ESM-CHEM"	},
    {	id:	"CMIP5Model47",	label:	"MIROC4h"	},
    {	id:	"CMIP5Model48",	label:	"MIROC5"	},
    {	id:	"CMIP5Model49",	label:	"MPI-ESM-LR"	},
    {	id:	"CMIP5Model50",	label:	"MPI-ESM-MR"	},
    {	id:	"CMIP5Model51",	label:	"MPI-ESM-P"	},
    {	id:	"CMIP5Model52",	label:	"MRI-AGCM3.2H"	},
    {	id:	"CMIP5Model53",	label:	"MRI-AGCM3.2S"	},
    {	id:	"CMIP5Model54",	label:	"MRI-CGCM3"	},
    {	id:	"CMIP5Model55",	label:	"MRI-ESM1"	},
    {	id:	"CMIP5Model56",	label:	"NICAM-09"	},
    {	id:	"CMIP5Model57",	label:	"NorESM1-M"	},
    {	id:	"CMIP5Model58",	label:	"NorESM1-ME"	},
    {	id:	"CMIP5Model59",	label:	"ULAQ"	},
    
]

export default CMIP5Model